# Predict expected time of delivery(dlvry_time)
**dlvry_time = time of order ---> time of delivery**

## Read data

In [1]:
DATA_READ_PATH = '/Users/calvinperumalla/personal project/Master - Data Scientist, ML Project 6'
import os

In [2]:
# load feature description --- sliced and diced data description wrote out pandas df loadable csv 
import pandas as pd
feature_description = pd.read_csv(os.path.join(DATA_READ_PATH, 'feature_description.csv'))[['feature', 'description']].drop_duplicates(subset='feature').to_dict()
index = list(feature_description['description'].keys())
feature_description = {feature_description['feature'][i]:feature_description['description'][i] for i in index}

In [3]:
# read data 
train_data = pd.read_csv(os.path.join(DATA_READ_PATH,'historical_data.csv'))

In [4]:
#train_data.dtypes
display(train_data)

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration
0,1.0,2015-02-06 22:24:17,2015-02-06 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0
1,2.0,2015-02-10 21:49:25,2015-02-10 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0
2,3.0,2015-01-22 20:39:28,2015-01-22 21:09:09,5477,NaN,1.0,1,1900,1,1900,1900,1.0,0.0,0.0,446,690.0
3,3.0,2015-02-03 21:21:45,2015-02-03 22:13:00,5477,NaN,1.0,6,6900,5,600,1800,1.0,1.0,2.0,446,289.0
4,3.0,2015-02-15 02:40:36,2015-02-15 03:20:26,5477,NaN,1.0,3,3900,3,1100,1600,6.0,6.0,9.0,446,650.0
5,3.0,2015-01-28 20:30:38,2015-01-28 21:08:58,5477,NaN,1.0,3,5000,3,1500,1900,2.0,2.0,2.0,446,338.0
6,3.0,2015-01-31 02:16:36,2015-01-31 02:43:00,5477,NaN,1.0,2,3900,2,1200,2700,10.0,9.0,9.0,446,638.0
7,3.0,2015-02-12 03:03:35,2015-02-12 03:36:20,5477,NaN,1.0,4,4850,4,750,1800,7.0,8.0,7.0,446,626.0
8,2.0,2015-02-16 00:11:35,2015-02-16 00:38:01,5477,indian,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0
9,3.0,2015-02-18 01:15:45,2015-02-18 02:08:57,5477,NaN,1.0,2,2100,2,700,1200,2.0,2.0,2.0,446,715.0
10,3.0,2015-02-02 19:22:53,2015-02-02 20:09:19,5477,NaN,4.0,4,4300,4,1200,1500,1.0,1.0,1.0,446,453.0
11,3.0,2015-02-16 04:19:33,2015-02-16 06:34:00,5477,NaN,1.0,2,2200,2,600,1600,3.0,3.0,4.0,446,642.0
12,3.0,2015-02-07 01:34:31,2015-02-07 02:17:14,5477,NaN,1.0,1,1900,1,1900,1900,6.0,3.0,3.0,446,690.0
13,3.0,2015-01-25 01:50:51,2015-01-25 02:28:53,5477,NaN,4.0,4,4986,4,699,2362,16.0,6.0,9.0,446,445.0
14,1.0,2015-02-12 03:36:46,2015-02-12 04:14:39,2841,italian,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0
15,1.0,2015-01-27 02:12:36,2015-01-27 03:02:24,2841,italian,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0
16,1.0,2015-02-06 00:42:42,2015-02-06 02:10:29,2841,italian,1.0,3,4475,3,925,1825,4.0,1.0,1.0,446,542.0
17,1.0,2015-02-08 02:04:17,2015-02-08 03:27:13,2841,italian,1.0,3,4375,3,1325,1625,6.0,4.0,3.0,446,789.0
18,1.0,2015-01-31 04:35:54,2015-01-31 05:47:30,2841,italian,1.0,2,3150,2,1425,1725,4.0,9.0,12.0,446,548.0
19,1.0,2015-01-31 02:21:23,2015-01-31 03:11:42,4139,mexican,1.0,2,950,2,150,700,24.0,24.0,26.0,446,212.0
20,1.0,2015-01-31 23:45:12,2015-02-01 00:14:05,4139,mexican,1.0,5,1285,3,150,400,12.0,13.0,11.0,446,424.0
21,1.0,2015-02-17 03:13:20,2015-02-17 04:00:31,5058,italian,1.0,4,5800,4,700,2000,19.0,19.0,30.0,446,344.0
22,1.0,2015-02-15 01:26:20,2015-02-15 02:16:07,5058,italian,1.0,2,2800,2,1200,1600,21.0,17.0,16.0,446,421.0
23,1.0,2015-02-02 05:27:49,2015-02-02 07:05:09,5058,italian,1.0,7,14900,5,1200,3900,8.0,11.0,11.0,446,901.0
24,1.0,2015-02-16 02:21:20,2015-02-16 03:54:14,5058,italian,1.0,3,3400,3,1400,2100,22.0,21.0,39.0,446,501.0
25,1.0,2015-02-13 01:01:58,2015-02-13 01:40:09,5058,italian,1.0,3,3800,3,700,1600,16.0,9.0,7.0,446,344.0
26,1.0,2015-01-24 02:01:20,2015-01-24 02:46:13,5058,italian,1.0,1,1800,1,1800,1800,27.0,25.0,24.0,446,424.0
27,1.0,2015-02-10 04:36:39,2015-02-10 05:20:37,5058,italian,1.0,4,5800,4,700,2000,13.0,16.0,27.0,446,344.0
28,1.0,2015-01-26 02:09:48,2015-01-26 02:47:22,5058,italian,1.0,3,3800,3,800,1800,21.0,18.0,20.0,446,530.0
29,1.0,2015-02-07 01:44:26,2015-02-07 02:48:06,5058,italian,1.0,1,1800,1,1800,1800,22.0,21.0,20.0,446,434.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197398,1.0,2015-02-18 02:56:01,2015-02-18 03:53:53,2956,fast,4.0,4,2274,4,345,675,55.0,52.0,66.0,251,574.0
197399,1.0,2015-02-09 22:05:33,2015-02-09 23:09:41,2956,fast,4.0,7,2863,4,329,505,16.0,16.0,15.0,251,901.0
197400,1.0,2015-02-06 19:35:47,2015-02-06 20:33:29,2956,fast,4.0,2,1401,2,691,755,37.0,27.0,39.0,251,690.0
197401,1.0,2015-02-02 21:48:55,2015-02-02 22:44:04,2956,fast,4.0,2,1049,2,300,669,23.0,26.0,37.0,251,546.0
197402,1.0,2015-01-28 03:15:02,2015-01-28 04:01:10,2956,fast,4.0,3,1940,3,339,499,48.0,48.0,55.0,251,531.0
197403,1.0,2015-02-05 21:12:07,2015-02-05 21:47:29,2956,fast,4.0,1,649,1,649,649,24.0,27.0,28.0,251,652.0
197404,1.0,2015-01-26 20:11:34,2015-01-26 20:55:36,2956,fast,4.0,4,1546,3,369,399,30.0,30.0,31.0,251,898.0
197405,1.0,2015-02-06 00:54:20,2015-02-06 01:52:32,2956,fast,4.0,7,3438,5,159,649,20.0,21.0,24.0,251,902.0
197406,1.0,2015-02-09 21:01:27,2015-02-09 21:38:08,2956,fast,4.0,1,649,1,649,649,26.0,19.0,21.0,251,652.0
197407,4.0,2015-01-27 04:55:25,2015-01-27 05:24:39,2956,seafood,5.0,2,1468,2,639,669,15.0,14.0,13.0,251,593.0
197408,1.0,2015-01-22 02:06:18,2015-01-22 02:49:17,2956,fast,4.0,6,2042,4,145,499,40.0,42.0,62.0,251,629.0
197409,1.0,2015-01-22 03:27:08,2015-01-22 04:03:18,2956,fast,4.0,1,719,1,639,639,53.0,39.0,42.0,251,628.0
197410,1.0,2015-02-09 20:32:27,2015-02-09 21:09:10,2956,fast,4.0,1,437,1,497,448,36.0,26.0,27.0,251,314.0
197411,1.0,2015-02-02 17:50:23,2015-02-02 18:12:57,2956,fast,4.0,2,1297,2,369,639,5.0,6.0,7.0,251,186.0
197412,1.0,2015-02-10 23:43:08,2015-02-11 00:47:24,2956,fast,4.0,1,674,1,345,345,10.0,11.0,12.0,251,706.0
197413,1.0,2015-01-24 01:33:11,2015-01-24 02:02:03,2956,fast,4.0,1,669,1,669,669,56.0,45.0,45.0,251,730.0
197414,1.0,2015-02-03 02:07:26,2015-02-03 04:22:00,2956,fast,4.0,5,2325,5,307,610,48.0,44.0,66.0,251,898.0
197415,1.0,2015-02-07 03:13:16,2015-02-07 04:29:49,2956,fast,4.0,3,1952,3,345,505,69.0,69.0,94.0,251,551.0
197416,1.0,2015-01-29 19:39:17,2015-01-29 20:34:21,2956,fast,4.0,1,639,1,639,639,26.0,26.0,37.0,251,NaN
197417,1.0,2015-01-29 01:41:57,2015-01-29 02:40:45,2956,fast,4.0,3,1398,3,200,639,38.0,38.0,49.0,251,899.0
197418,1.0,2015-01-30 20:50:23,2015-01-30 22:24:38,2956,fast,4.0,2,1528,2,639,729,26.0,29.0,34.0,251,791.0
197419,1.0,2015-01-26 21:25:12,2015-01-26 22:21:22,2956,fast,4.0,1,809,1,729,729,20.0,18.0,18.0,251,818.0
197420,2.0,2015-02-18 02:16:04,2015-02-18 03:12:36,2956,indian,3.0,3,2352,3,499,685,49.0,49.0,65.0,251,560.0
197421,1.0,2015-01-30 03:35:01,2015-01-30 04:42:19,2956,fast,4.0,2,979,2,145,339,NaN,NaN,NaN,251,614.0
197422,1.0,2015-01-31 19:48:15,2015-01-31 20:27:39,2956,fast,4.0,7,2445,3,145,585,23.0,24.0,24.0,251,608.0
197423,1.0,2015-02-17 00:19:41,2015-02-17 01:24:48,2956,fast,4.0,3,1389,3,345,649,17.0,17.0,23.0,251,331.0
197424,1.0,2015-02-13 00:01:59,2015-02-13 00:58:22,2956,fast,4.0,6,3010,4,405,825,12.0,11.0,14.0,251,915.0
197425,1.0,2015-01-24 04:46:08,2015-01-24 05:36:16,2956,fast,4.0,5,1836,3,300,399,39.0,41.0,40.0,251,795.0
197426,1.0,2015-02-01 18:18:15,2015-02-01 19:23:22,3630,sandwich,1.0,1,1175,1,535,535,7.0,7.0,12.0,446,384.0
197427,1.0,2015-02-08 19:24:33,2015-02-08 20:01:41,3630,sandwich,1.0,4,2605,4,425,750,20.0,20.0,23.0,446,134.0

In [5]:
# easy look up of description of feature
feature_description['total_outstanding_orders']

' Number of orders within 10 miles of this order that are currently being processed.'

In [6]:
# create a column of what we want to actually predict: the time taken to from the time of placing the order,
# to a dasher picking it up (pick_up_time): 
# Total_delivery_time = estimated_order_place_duration (Known) + pick_up_time + estimated_store_to_consumer_driving_duration(Known)

from datetime import datetime
train_data['pick_up_time'] = (pd.to_datetime(train_data['actual_delivery_time']) - pd.to_datetime(train_data['created_at']))
train_data['pick_up_time'] = train_data['pick_up_time'].apply(lambda x: x.total_seconds()) - train_data['estimated_order_place_duration'] - train_data['estimated_store_to_consumer_driving_duration']

## Feature Engineering

**use statistical tests to determine best features**

In [7]:
# to remove noise
import numpy as np
from tqdm import tqdm
def filter_noise(df, features, noise_threshold=99):
    tmp_df = None
    for f in tqdm(features):
        if tmp_df is None:
            tmp_df = df
        upper = np.percentile(tmp_df[f], noise_threshold)
        tmp_df = tmp_df[tmp_df[f]< upper]
    return tmp_df

In [8]:
from sklearn.feature_selection import SelectKBest, f_regression, mutual_info_regression
try:
    before = len(train_data)
    train_data_dropna = train_data.dropna()
    after_na = len(train_data_dropna)
    train_data_dropna.drop(['actual_delivery_time', 'created_at', 'store_primary_category'], axis=1, inplace=True)
    #train_data_filter = filter_noise(train_data_dropna, train_data_dropna.columns)
    train_data_filter = filter_noise(train_data_dropna, ['pick_up_time'])
    after = len(train_data_filter)
    print('original data set size: {} instances \nafter dropping rows with nan: {}, \nafter removing noise: {} instances'.format(before, after_na, after))
except ValueError:
    raise(e)
    pass

features = train_data_filter.drop(['pick_up_time'], axis=1)
labels = train_data_filter['pick_up_time']

# NOTE: tried with f_regression and got results that were not better than previous results

X_new = SelectKBest(f_regression, k=4).fit_transform(features, labels.astype(int))

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

100%|██████████| 1/1 [00:00<00:00, 107.69it/s]

original data set size: 197428 instances
after dropping rows with nan: 175777,
after removing noise: 174018 instances

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/utils/__init__.py:93: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(mask.dtype, np.int):

## Approach: Bunch of Non Linear Methods
### Random forest regressor
1. Features: calculated by f regression score 
2. Classifier: non linear random forest regressor
3. Validation: 4 fold validation
4. Metric: R2 score

#### Train linear regression model

In [9]:
from sklearn.ensemble import RandomForestRegressor
cls = RandomForestRegressor(n_estimators=20)

In [10]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
kfold = KFold(n_splits=5)
model_predictions = {}
model_performance = {}
model_run_index = 0
y = labels.astype(int)
for train_index, test_index in tqdm(kfold.split(X_new)):
    model_run_index += 1
    regressor = LinearRegression()
    train_x = X_new[train_index]
    train_y = y.iloc[train_index]
    #print(any([any(np.isnan(inst)) for inst in train_x]))
    #print(any([np.isnan(inst) for inst in train_y]), 'y')
    model = cls.fit(train_x, train_y)
    test_x = X_new[test_index]
    test_y = y.iloc[test_index]
    predictions = model.predict(test_x)
    model_name = 'run_{}'.format(model_run_index)
    model_predictions[model_name] = zip(test_y.values, predictions)
    model_performance[model_name] = model.score(test_x, test_y)

5it [00:44,  8.99s/it]

In [11]:
# choosing best model
model_performance

{'run_1': -0.05093066805380175,
 'run_2': -0.04615306132489727,
 'run_3': -0.04708895384660061,
 'run_4': -0.05567969776816284,
 'run_5': -0.05343689485035097}

In [12]:
from matplotlib import pyplot as plt
true, pred = zip(*model_predictions['run_1'])
mx = int(max(max(true), max(pred)))
plt.figure(figsize=(10, 10))
plt.plot(list(range(mx)), list(range(mx)))
plt.scatter(true, pred)
plt.title('truth vs predictions')
plt.xlabel('truth')
plt.ylabel('predictions')
plt.grid()
plt.show()

### linear regression with non linear features
Features: calculated by f regression score
New features: Add non linear variables (xi^2, xi\*xj)
Classifier: linear regression
Validation: 4 fold validation
Metric: R2 score

In [13]:
import numpy as np
def make_new_features(data):
    squared_data = np.square(data)
    cubed_data = np.power(data, 3)
    inverse_data =  (data + 0.5) ** float(-1)
    res = np.append(data, squared_data, axis=1)
    res = np.append(res, inverse_data, axis=1)
    res = np.append(res, cubed_data, axis=1)
    np.nan_to_num(res, copy=False)
    #res[np.isinf(res)] = 0.0
    return res

In [14]:
#make_new_features(test)

In [15]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

def make_model(X, y, classifier):
    model_predictions = {}
    model_performance = {}
    model_run_index = 0
    kfold = KFold(n_splits=5)
    for train_index, test_index in tqdm(kfold.split(X)):
        model_run_index += 1
        train_x = X[train_index]
        train_y = y.iloc[train_index]
        #print(any([any(np.isnan(inst)) for inst in train_x]))
        #print(any([np.isnan(inst) for inst in train_y]), 'y')
        model = classifier.fit(train_x, train_y)
        test_x = X_poly[test_index]
        test_y = y.iloc[test_index]
        predictions = model.predict(test_x)
        model_name = 'run_{}'.format(model_run_index)
        model_predictions[model_name] = zip(test_y.values, predictions)
        model_performance[model_name] = model.score(test_x, test_y)
    return model_predictions, model_performance, model.coef_

In [ ]:
X_poly = make_new_features(X_new)
y = labels.astype(int)
regressor = LinearRegression()
predictions, performance, coeffs = make_model(X_poly, y, regressor)

In [ ]:
from matplotlib import pyplot as plt
true, pred = zip(*predictions['run_1'])
mx = int(max(max(true), max(pred)))
plt.figure(figsize=(10, 10))
plt.plot(list(range(mx)), list(range(mx)))
plt.scatter(true, pred)
plt.title('truth vs predictions')
plt.xlabel('truth')
plt.ylabel('predictions')
plt.grid()
plt.show()